<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/src/bootstrap.php';
require_once __DIR__.'/_data.php';
$user=Auth::requireLogin();
if(!Auth::canForUser($user,'meals_manage')) { http_response_code(403); exit('Kein Zugriff.'); }
$data=bistro_fetch_meals($_GET);
function row_html(array $b): string { $m=$b['_meal']??['status_label'=>'offen']; return '<tr><td>'.e((string)($b['apartment_name']?:'Nicht zugeordnet')).'</td><td><b>'.e((string)$b['guest_name']).'</b><br><small>'.e((string)$b['reference']).'</small></td><td>'.(int)$b['adults'].'</td><td>'.(int)$b['children'].'</td><td>'.e((string)($b['guest_category_name']??'')).'</td><td>'.e((string)$m['status_label']).'</td><td>'.e((string)($b['special_requests'] ?: $b['notes'] ?: '')).'</td></tr>'; }
?><!doctype html><html lang="de"><head><meta charset="utf-8"><title>Bistro Druckliste</title><style>body{font-family:Arial,sans-serif;margin:24px;color:#111827}h1{margin:0 0 6px}.muted{color:#64748b}.day{break-inside:avoid;margin:22px 0}table{width:100%;border-collapse:collapse;margin:8px 0 18px}th,td{border:1px solid #dbe4f0;padding:7px;text-align:left;vertical-align:top}th{background:#f1f5f9}.sum{font-weight:bold;background:#fff7ed}.badge{display:inline-block;border:1px solid #ddd;border-radius:999px;padding:3px 7px;margin-left:6px}@media print{button{display:none}}</style></head><body><button onclick="window.print()">Drucken</button><h1>Frühstück & HP</h1><p class="muted">Zeitraum: <?=e($data['from'])?> bis <?=e($data['to'])?> · Status wird aus der Bistro-Abhakliste übernommen.</p><?php foreach($data['days'] as $day): ?><section class="day"><h2><?=e($day['weekday'])?>, <?=e($day['date'])?> <span class="badge">☕ <?=e((string)$day['summary']['breakfast_total'])?></span> <span class="badge">🍽️ <?=e((string)$day['summary']['half_total'])?></span></h2><?php if($data['service']!=='half_board'): ?><h3>Frühstück · <?=e((string)$day['summary']['breakfast_total'])?> Personen</h3><table><thead><tr><th>Wohnung</th><th>Gast</th><th>Erw.</th><th>Kinder</th><th>Kategorie</th><th>Status</th><th>Hinweise</th></tr></thead><tbody><?=implode('',array_map('row_html',$day['breakfast'])) ?: '<tr><td colspan="7">Keine Einträge.</td></tr>'?></tbody></table><?php endif; ?><?php if($data['service']!=='breakfast'): ?><h3>Halbpension · <?=e((string)$day['summary']['half_total'])?> Personen</h3><table><thead><tr><th>Wohnung</th><th>Gast</th><th>Erw.</th><th>Kinder</th><th>Kategorie</th><th>Status</th><th>Hinweise</th></tr></thead><tbody><?=implode('',array_map('row_html',$day['half_board'])) ?: '<tr><td colspan="7">Keine Einträge.</td></tr>'?></tbody></table><?php endif; ?></section><?php endforeach; ?></body></html>
