<?php
declare(strict_types=1);
require_once dirname(__DIR__) . '/src/bootstrap.php';
Auth::requireLogin();

function print_header(string $title, string $subtitle=''): void
{
    $property=(string)setting('property_name','StayPilot');
    ?><!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($title)?> – <?=e($property)?></title>
    <style>
    *{box-sizing:border-box}body{font-family:Arial,Helvetica,sans-serif;color:#172033;margin:0;background:#eef2f7;font-size:11px}.page{width:min(1180px,calc(100% - 30px));margin:20px auto;background:#fff;padding:25px;box-shadow:0 10px 30px rgba(0,0,0,.09)}.head{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #172033;padding-bottom:12px;margin-bottom:16px}.head h1{font-size:22px;margin:0 0 4px}.head p{margin:0;color:#5f6b7d}.meta{text-align:right;line-height:1.45}.tools{display:flex;gap:8px;margin-bottom:14px;flex-wrap:wrap}.btn{background:#2563eb;color:#fff;text-decoration:none;border:0;border-radius:8px;padding:9px 12px;font-weight:bold;cursor:pointer}.btn.light{background:#e8edf5;color:#172033}table{width:100%;border-collapse:collapse;margin:8px 0 18px;font-size:10px}th,td{border:1px solid #cfd8e6;padding:6px 7px;vertical-align:top;text-align:left}th{background:#eef3f9;text-transform:uppercase;font-size:9px;letter-spacing:.04em}.date-title{font-size:15px;margin:18px 0 7px;padding:8px 10px;background:#172033;color:#fff;break-after:avoid}.summary{display:flex;gap:14px;flex-wrap:wrap;margin:8px 0 15px}.summary span{border:1px solid #cfd8e6;border-radius:8px;padding:7px 10px;background:#f8fafc}.check{font-size:16px}.muted{color:#6b7280}.signature{height:38px;border-bottom:1px solid #172033;min-width:130px}.no-data{padding:25px;border:1px dashed #9aa7b8;text-align:center;color:#6b7280}.page-break{page-break-before:always}.section{margin:14px 0}.legal-note{border:1px solid #cfd8e6;background:#f8fafc;padding:9px;margin-top:14px;line-height:1.45}.two{display:grid;grid-template-columns:1fr 1fr;gap:14px}.fieldbox{border:1px solid #cfd8e6;padding:7px;min-height:39px}.fieldbox b{display:block;font-size:8px;text-transform:uppercase;color:#6b7280;margin-bottom:4px}.traveller-card{border:1px solid #9aa7b8;padding:12px;margin:12px 0;break-inside:avoid}.traveller-card h3{margin:0 0 10px;font-size:14px}.checkbox{display:inline-block;width:14px;height:14px;border:1px solid #172033;vertical-align:middle;margin-right:4px}@page{size:A4 landscape;margin:10mm}@media print{body{background:#fff}.page{width:auto;margin:0;padding:0;box-shadow:none}.tools{display:none}.date-title{background:#ddd!important;color:#000!important;-webkit-print-color-adjust:exact;print-color-adjust:exact}th{background:#eee!important;-webkit-print-color-adjust:exact;print-color-adjust:exact}}@media(max-width:700px){.two{grid-template-columns:1fr}.page{width:100%;margin:0;padding:15px}.head{display:block}.meta{text-align:left;margin-top:8px}}
    </style></head><body><main class="page"><div class="tools"><button type="button" class="btn" data-print-page>🖨 Drucken</button><button type="button" class="btn light" data-history-back>← Zurück</button></div><header class="head"><div><h1><?=e($title)?></h1><?php if($subtitle):?><p><?=e($subtitle)?></p><?php endif?></div><div class="meta"><b><?=e($property)?></b><br><?=e((string)setting('full_address',''))?><br><?=e(trim((string)setting('postal_code','').' '.(string)setting('city','')))?></div></header><?php
}
function print_footer(): void { ?><div class="muted" style="margin-top:16px">Erstellt mit StayPilot am <?=e(date('d.m.Y H:i'))?></div></main><script>document.querySelector('[data-print-page]')?.addEventListener('click',()=>window.print());document.querySelector('[data-history-back]')?.addEventListener('click',()=>history.back());</script></body></html><?php }
