<?php
declare(strict_types=1);
require_once __DIR__.'/_print_common.php';
$id = (int)($_GET['booking_id'] ?? 0);
$booking = CheckinDocumentService::bookingRow($id);
$bundle = CheckinService::bundle($id);
$c = $bundle['checkin'];
print_header('Meldeschein / Gästeregister', 'Buchung ' . (string)$booking['reference'] . ' · ' . (string)$booking['arrival'] . ' bis ' . (string)$booking['departure']);
?>
<div class="two"><div class="fieldbox"><b>Beherbergungsbetrieb</b><?=e((string)setting('legal_name',setting('property_name','StayPilot')))?> · <?=e((string)setting('tax_id',''))?><br><?=e((string)setting('full_address',''))?>, <?=e(trim((string)setting('postal_code','').' '.(string)setting('city','')))?></div><div class="fieldbox"><b>Unterkunft</b><?=e((string)($booking['apartment_code'] ?: '–'))?> · <?=e((string)($booking['apartment_name'] ?: $booking['apartment_type_name']))?><br>Anreisezeit: <?=e(substr((string)($c['planned_arrival_time'] ?? $booking['planned_arrival_time'] ?? ''),0,5) ?: '–')?> · Kennzeichen: <?=e((string)($c['vehicle_plate'] ?? $booking['vehicle_plate'] ?? '–'))?></div></div>
<?php foreach(($bundle['travellers'] ?? []) as $i=>$t): ?><article class="traveller-card"><h3>Reisende Person <?=($i+1)?><?=(int)($t['is_primary']??0)?' · Hauptgast':''?></h3><div class="two"><div class="fieldbox"><b>Name</b><?=e(trim((string)$t['first_name'].' '.(string)$t['last_name'].' '.(string)($t['second_last_name']??'')))?></div><div class="fieldbox"><b>Geschlecht / Geburtsdatum</b><?=e((string)($t['gender']??''))?> · <?=e((string)($t['date_of_birth']??''))?></div><div class="fieldbox"><b>Dokument</b><?=e((string)($t['document_type']??''))?> · <?=e((string)($t['document_number']??''))?> · Support: <?=e((string)($t['document_support_number']??''))?></div><div class="fieldbox"><b>Dokumentausstellung</b><?=e((string)($t['document_issue_date']??''))?> · <?=e((string)($t['document_country']??''))?></div><div class="fieldbox"><b>Geburtsort / Provinz</b><?=e((string)($t['place_of_birth']??''))?> · <?=e((string)($t['province']??''))?></div><div class="fieldbox"><b>Nationalität</b><?=e((string)($t['nationality']??''))?></div><div class="fieldbox"><b>Anschrift</b><?=e((string)($t['address']??''))?>, <?=e((string)($t['postal_code']??''))?> <?=e((string)($t['city']??''))?>, <?=e((string)($t['country']??''))?></div><div class="fieldbox"><b>Kontakt</b><?=e((string)($t['mobile_phone']??''))?> · <?=e((string)($t['fixed_phone']??''))?> · <?=e((string)($t['email']??''))?></div><div class="fieldbox"><b>Beziehung / minderjährig</b><?=e((string)($t['relationship_to_primary']??''))?> · <?=((int)($t['minor']??0)?'Ja':'Nein')?></div><div class="fieldbox"><b>Unterschriftsstatus</b><?=e((string)($t['signature_status']??'open'))?></div></div><div style="margin-top:20px;display:grid;grid-template-columns:1fr 230px;gap:30px;align-items:end"><div><b>Unterschrift der reisenden Person / gesetzlichen Vertretung</b><div class="signature"></div></div><div><b>Datum</b><div class="signature"></div></div></div></article><?php endforeach; if(empty($bundle['travellers'])): ?><div class="no-data">Noch keine reisenden Personen erfasst.</div><?php endif; ?>
<div class="legal-note">Diese Druckansicht ist eine interne Gästeregister- und Meldeschein-Hilfe. Prüfen Sie vor einer behördlichen Übermittlung die Vollständigkeit sowie die aktuell geltenden Vorgaben und das von der zuständigen Behörde geforderte Übermittlungsformat.</div>
<?php print_footer();
