<?php
declare(strict_types=1);
require_once __DIR__.'/_print_common.php';
$id=(int)($_GET['booking_id']??0);$stmt=db()->prepare("SELECT b.*,CONCAT(g.first_name,' ',g.last_name) guest_name,a.name apartment_name,a.code apartment_code FROM bookings b JOIN guests g ON g.id=b.guest_id LEFT JOIN apartments a ON a.id=b.apartment_id WHERE b.id=?");$stmt->execute([$id]);$booking=$stmt->fetch();if(!$booking){http_response_code(404);exit('Buchung nicht gefunden.');}
$stmt=db()->prepare('SELECT * FROM booking_travellers WHERE booking_id=? ORDER BY is_primary DESC,id');$stmt->execute([$id]);$travellers=$stmt->fetchAll();
print_header('Polizeiliches Gästeregister / Meldedaten','Buchung '.(string)$booking['reference'].' · '.(new DateTimeImmutable($booking['arrival']))->format('d.m.Y').' bis '.(new DateTimeImmutable($booking['departure']))->format('d.m.Y'));
?><div class="two"><div class="fieldbox"><b>Beherbergungsbetrieb</b><?=e((string)setting('legal_name',setting('property_name','')))?> · <?=e((string)setting('tax_id',''))?><br><?=e((string)setting('full_address',''))?>, <?=e((string)setting('postal_code','').' '.(string)setting('city',''))?></div><div class="fieldbox"><b>Registrierung / Unterkunft</b><?=e((string)setting('police_registration_number','–'))?><br><?=e(($booking['apartment_code']?:'–').' · '.($booking['apartment_name']?:'Nicht zugeordnet'))?></div></div>
<div class="summary"><span>Anreise: <b><?=e((new DateTimeImmutable($booking['arrival']))->format('d.m.Y'))?></b></span><span>Abreise: <b><?=e((new DateTimeImmutable($booking['departure']))->format('d.m.Y'))?></b></span><span>Personen laut Buchung: <b><?=((int)$booking['adults']+(int)$booking['children']+(int)$booking['babies'])?></b></span><span>Meldestatus: <b><?=e((string)$booking['police_status'])?></b></span></div>
<?php if(!$travellers):?><div class="no-data">Noch keine reisenden Personen erfasst. Öffnen Sie die Buchung und wählen Sie „Reisende / Meldedaten“.</div><?php endif?>
<?php foreach($travellers as $i=>$t):?><article class="traveller-card"><h3>Reisende Person <?=($i+1)?><?=(int)$t['is_primary']?' · Hauptgast':''?></h3><div class="two"><div class="fieldbox"><b>Name</b><?=e(trim($t['first_name'].' '.$t['last_name'].' '.($t['second_last_name']??'')))?></div><div class="fieldbox"><b>Geschlecht / Geburtsdatum</b><?=e((string)$t['gender'])?> · <?=e($t['date_of_birth']?(new DateTimeImmutable($t['date_of_birth']))->format('d.m.Y'):'')?></div><div class="fieldbox"><b>Dokument</b><?=e((string)$t['document_type'])?> · <?=e((string)$t['document_number'])?> · Support: <?=e((string)$t['document_support_number'])?></div><div class="fieldbox"><b>Dokumentausstellung</b><?=e($t['document_issue_date']?(new DateTimeImmutable($t['document_issue_date']))->format('d.m.Y'):'')?> · <?=e((string)$t['document_country'])?></div><div class="fieldbox"><b>Geburtsort / Provinz</b><?=e((string)$t['place_of_birth'])?> · <?=e((string)$t['province'])?></div><div class="fieldbox"><b>Nationalität</b><?=e((string)$t['nationality'])?></div><div class="fieldbox"><b>Anschrift</b><?=e((string)$t['address'])?>, <?=e((string)$t['postal_code'].' '.(string)$t['city'])?>, <?=e((string)$t['country'])?></div><div class="fieldbox"><b>Kontakt</b><?=e((string)$t['mobile_phone'])?> · <?=e((string)$t['fixed_phone'])?> · <?=e((string)$t['email'])?></div><div class="fieldbox"><b>Beziehung / minderjährig</b><?=e((string)$t['relationship_to_primary'])?> · <?=((int)$t['minor']?'Ja':'Nein')?></div><div class="fieldbox"><b>Unterschriftsstatus</b><?=e((string)$t['signature_status'])?></div></div><div style="margin-top:20px;display:grid;grid-template-columns:1fr 230px;gap:30px;align-items:end"><div><b>Unterschrift der reisenden Person / gesetzlichen Vertretung</b><div class="signature"></div></div><div><b>Datum</b><div class="signature"></div></div></div></article><?php endforeach?>
<div class="legal-note">Diese Druckansicht ist ein internes Gästeregister und eine Arbeitshilfe. Prüfen Sie vor einer behördlichen Übermittlung die Vollständigkeit sowie die aktuell geltenden Vorgaben und das von der zuständigen Behörde geforderte Übermittlungsformat.</div>
<?php print_footer();
