<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/src/bootstrap.php';
$user=Auth::requireLogin();
$role=(string)($user['role']??'readonly');
$previewMemberId=in_array($role,['admin','manager','reception'],true)?((int)($_GET['preview_member_id']??0)?:null):null;
if ($role==='housekeeping_manager') { header('Location: ../team-manager/'); exit; }
if (!in_array($role,['housekeeping','admin','manager','reception'],true)) { header('Location: ../admin/'); exit; }

if ($role !== 'housekeeping' && !$previewMemberId) {
    $stmt = db()->query("SELECT hm.id,hm.name,hm.email,hm.whatsapp_number,hm.active,ht.name team_name,
        (SELECT COUNT(*) FROM housekeeping_tasks t WHERE t.member_id=hm.id AND t.task_date BETWEEN CURDATE() AND DATE_ADD(CURDATE(), INTERVAL 7 DAY)) task_count
        FROM housekeeping_members hm
        LEFT JOIN housekeeping_teams ht ON ht.id=hm.team_id
        WHERE hm.active=1
        ORDER BY COALESCE(ht.name,''),hm.name");
    $members = $stmt->fetchAll();
    $version=(string)(config()['app_version'] ?? '2.3.6.37');
    ?>
<!doctype html>
<html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>StayPilot Team-Vorschau</title><link rel="stylesheet" href="../assets/portal.css?v=<?=e($version)?>"><style>body{background:#f3f7fb}.preview-wrap{max-width:1050px;margin:32px auto;padding:0 18px}.preview-head{background:linear-gradient(135deg,#2563eb,#0f766e);color:#fff;border-radius:24px;padding:28px;box-shadow:0 20px 45px rgba(15,23,42,.14)}.preview-head h1{margin:0 0 8px;font-size:32px}.preview-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:14px;margin-top:18px}.member-card{background:#fff;border:1px solid #dbe4f0;border-radius:18px;padding:16px;box-shadow:0 8px 24px rgba(15,23,42,.06)}.member-card b{display:block;font-size:18px}.member-card small{color:#64748b}.member-card .meta{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.pill{background:#eef5ff;border:1px solid #dbe4f0;border-radius:999px;padding:5px 9px;font-weight:700;font-size:12px}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:16px}.btn{display:inline-flex;align-items:center;justify-content:center;text-decoration:none;border:1px solid #dbe4f0;border-radius:12px;padding:10px 12px;font-weight:900;color:#132033;background:#fff}.btn.primary{background:#2563eb;border-color:#2563eb;color:#fff}.notice{background:#fffbeb;border:1px solid #fde68a;color:#92400e;border-radius:16px;padding:12px 14px;margin-top:14px;font-weight:700}.empty{background:#fff;border:1px dashed #cbd5e1;border-radius:18px;padding:24px;text-align:center;color:#64748b;margin-top:18px}</style></head><body>
<div class="preview-wrap">
  <section class="preview-head"><h1>StayPilot Team-Vorschau</h1><p>Du bist als <?=e((string)($user['name'] ?? 'Admin'))?> angemeldet. Wähle eine Reinigungskraft, um das bestehende Team-Portal als Vorschau zu öffnen.</p><div class="actions"><a class="btn" href="../housekeeping/login.php">Zurück zum Housekeeping-Login</a><a class="btn" href="../team-manager/">Zur Leitung</a><a class="btn" href="../admin/#housekeeping">Admin-Putzplan</a></div></section>
  <div class="notice">Diese Ansicht ist keine zweite Team-App. Sie nutzt das bestehende Mitarbeiterportal als Admin-/Rezeptions-Vorschau. Speichern von Mitarbeiteraktionen bleibt in der Vorschau gesperrt.</div>
  <?php if (!$members): ?><div class="empty">Noch keine aktiven Housekeeping-Mitarbeiter angelegt.</div><?php else: ?>
  <section class="preview-grid">
    <?php foreach ($members as $m): ?>
      <article class="member-card"><b><?=e((string)$m['name'])?></b><small><?=e((string)($m['team_name'] ?: 'Ohne Team'))?></small><div class="meta"><span class="pill"><?= (int)$m['task_count'] ?> Aufgaben 7 Tage</span><?php if(!empty($m['email'])): ?><span class="pill">E-Mail</span><?php endif; ?><?php if(!empty($m['whatsapp_number'])): ?><span class="pill">WhatsApp</span><?php endif; ?></div><a class="btn primary" href="?preview_member_id=<?= (int)$m['id'] ?>">Team-Portal öffnen</a></article>
    <?php endforeach; ?>
  </section><?php endif; ?>
</div></body></html><?php
    exit;
}
$memberIdentity=$role==='housekeeping' ? HousekeepingWorkflow::memberForUser((int)$user['id']) : null;
$identityLabel=$previewMemberId ? 'Mitarbeiter-Vorschau' : (($memberIdentity['name']??'') ?: ($user['name']??'Mitarbeiter'));
$version=(string)(config()['app_version'] ?? '2.2.0');
?>
<!doctype html><html lang="de"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#0f766e"><title>StayPilot – Meine Aufgaben</title><link rel="stylesheet" href="../assets/portal.css?v=<?=e($version)?>"></head><body>
<div class="portal-shell"><header class="portal-head"><div class="portal-brand"><div class="logo">🧹</div><div><b>StayPilot Team</b><small id="identityText"><?=e($identityLabel)?> · Meine Reinigungsaufträge</small></div></div><div class="portal-actions"><div class="language-switch"><button class="btn active" type="button" data-lang="de">DE</button><button class="btn" type="button" data-lang="es">ES</button></div><button class="btn hide-mobile" id="enableNotifications" type="button">🔔</button><div class="portal-app-switcher"><a class="btn" href="https://quartier-schweizer.de/">Vermietung</a><a class="btn" href="https://quartier-schweizer.de/nebenkosten/">Nebenkosten</a></div><a class="btn" href="../logout.php?portal=team" data-i18n="logout">Abmelden</a></div></header><main class="portal-main"><div class="portal-toolbar"><button class="btn primary" data-range="today">Heute</button><button class="btn" data-range="tomorrow">Morgen</button><button class="btn" data-range="week">7 Tage</button><button class="btn" id="refreshBtn">↻ Aktualisieren</button><span class="muted" id="updatedAt"></span></div><div id="message"></div><div class="portal-grid" id="taskGrid"><div class="portal-card empty">Aufgaben werden geladen …</div></div></main></div>
<dialog id="taskDialog"><div class="dialog-head"><div><b id="taskTitle">Auftrag</b><div class="muted" id="taskSubtitle"></div></div><button class="btn" data-close-dialog>✕</button></div><form id="taskForm"><div class="dialog-body" id="taskBody"></div><div class="dialog-foot"><button type="button" class="btn" data-close-dialog>Abbrechen</button><button type="submit" class="btn primary">Speichern</button></div></form></dialog>
<dialog id="incidentDialog"><div class="dialog-head"><div><b data-i18n="reportProblem">Problem melden</b></div><button class="btn" data-close-dialog>✕</button></div><form id="incidentForm" enctype="multipart/form-data"><div class="dialog-body"><input type="hidden" name="task_id" id="incidentTaskId"><div class="field"><label data-i18n="category">Kategorie</label><select name="category"><option value="defect" data-i18n="incidentDefect">Defekt</option><option value="damage" data-i18n="incidentDamage">Beschädigung</option><option value="vandalism" data-i18n="incidentVandalism">Vandalismus</option><option value="theft" data-i18n="incidentTheft">Diebstahlverdacht</option><option value="missing_inventory" data-i18n="incidentMissing">Fehlendes Inventar</option><option value="heavy_soiling" data-i18n="incidentSoiling">Starke Verschmutzung</option><option value="safety" data-i18n="incidentSafety">Sicherheitsproblem</option><option value="other" data-i18n="incidentOther">Sonstiges</option></select></div><div class="field"><label data-i18n="urgency">Dringlichkeit</label><select name="severity"><option value="low" data-i18n="severityLow">Niedrig</option><option value="normal" selected data-i18n="severityNormal">Normal</option><option value="high" data-i18n="severityHigh">Hoch</option><option value="critical" data-i18n="severityCritical">Kritisch</option></select></div><div class="field"><label><input type="checkbox" name="apartment_usable" value="1" checked> <span data-i18n="usable">Wohnung weiterhin nutzbar</span></label></div><div class="field"><label data-i18n="description">Beschreibung</label><textarea name="description" required></textarea></div><div class="field"><label data-i18n="photos">Fotos (optional)</label><input type="file" name="photos[]" accept="image/jpeg,image/png,image/webp" multiple></div></div><div class="dialog-foot"><button type="button" class="btn" data-close-dialog data-i18n="cancel">Abbrechen</button><button type="submit" class="btn danger" data-i18n="sendReport">Meldung senden</button></div></form></dialog>
<dialog id="inspectDialog"><div class="dialog-head"><b data-i18n="inspectTitle">Wohnung kontrollieren</b><button class="btn" data-close-dialog>✕</button></div><form id="inspectForm"><div class="dialog-body"><input type="hidden" name="id"><div class="field"><label data-i18n="result">Ergebnis</label><select name="result"><option value="passed" data-i18n="inspectionPassed">Kontrolle bestanden</option><option value="rework" data-i18n="reworkRequired">Nachreinigung erforderlich</option></select></div><div class="field"><label data-i18n="inspectionNote">Kontrollnotiz</label><textarea name="note"></textarea></div></div><div class="dialog-foot"><button type="button" class="btn" data-close-dialog data-i18n="cancel">Abbrechen</button><button type="submit" class="btn primary" data-i18n="saveInspection">Kontrolle speichern</button></div></form></dialog>
<dialog id="readyDialog"><div class="dialog-head"><b data-i18n="readyTitle">Bezugsbereit melden</b><button class="btn" data-close-dialog>✕</button></div><form id="readyForm"><div class="dialog-body"><input type="hidden" name="id"><div class="notice" data-i18n="readyInfo">Admin oder Rezeption erteilt danach die endgültige Gastfreigabe.</div><div class="field"><label data-i18n="readyNote">Hinweis</label><textarea name="note"></textarea></div></div><div class="dialog-foot"><button type="button" class="btn" data-close-dialog data-i18n="cancel">Abbrechen</button><button type="submit" class="btn success" data-i18n="readySubmit">Bezugsbereit melden</button></div></form></dialog>
<div class="toast-area" id="toastArea"></div>
<script>window.PORTAL={api:'api.php',csrf:'<?=e(csrf_token())?>',today:'<?=date('Y-m-d')?>',previewMemberId:<?=json_encode($previewMemberId)?>,pollSeconds:<?=max(10,(int)setting('housekeeping_poll_seconds',20))?>};</script><script src="team.js?v=<?=e($version)?>"></script></body></html>

