<?php
declare(strict_types=1);
require_once dirname(__DIR__).'/src/bootstrap.php';
Auth::requireRole(['housekeeping_manager','admin','manager','reception']);
$from=(string)($_GET['from']??date('Y-m-d'));$to=(string)($_GET['to']??date('Y-m-d',strtotime('+7 days')));
$lang=in_array((string)($_GET['lang']??'de'),['de','es'],true)?(string)$_GET['lang']:'de';
if(!valid_date($from)||!valid_date($to)||$from>$to)exit($lang==='es'?'Periodo no válido':'Ungültiger Zeitraum');
$tr=[
'de'=>['title'=>'Housekeeping-Arbeitsliste','print'=>'Drucken','date'=>'Datum','apartment'=>'Apartment','task'=>'Auftrag','assigned'=>'Zuständig','time'=>'Zeit','checklist'=>'Checkliste','status'=>'Status','open'=>'offen','minutes'=>'Min.'],
'es'=>['title'=>'Lista de trabajo de limpieza','print'=>'Imprimir','date'=>'Fecha','apartment'=>'Apartamento','task'=>'Tarea','assigned'=>'Asignado','time'=>'Tiempo','checklist'=>'Lista de control','status'=>'Estado','open'=>'sin asignar','minutes'=>'min.']
][$lang];
$stmt=db()->prepare("SELECT h.*,a.code apartment_code,a.name apartment_name,ht.name team_name,hm.name member_name FROM housekeeping_tasks h JOIN apartments a ON a.id=h.apartment_id LEFT JOIN housekeeping_teams ht ON ht.id=h.team_id LEFT JOIN housekeeping_members hm ON hm.id=h.member_id WHERE h.task_date BETWEEN ? AND ? ORDER BY h.task_date,h.due_time,a.name");$stmt->execute([$from,$to]);$rows=$stmt->fetchAll();
?><!doctype html><html lang="<?=e($lang)?>"><head><meta charset="utf-8"><title><?=e($tr['title'])?> <?=e($from)?>–<?=e($to)?></title><style>body{font-family:Arial,sans-serif;color:#172033}h1{margin-bottom:4px}.muted{color:#667085}table{width:100%;border-collapse:collapse;font-size:12px}th,td{border:1px solid #cbd5e1;padding:7px;vertical-align:top}th{background:#f1f5f9}.check{line-height:1.6}@media print{button{display:none}}</style></head><body><button type="button" id="printButton"><?=e($tr['print'])?></button><h1><?=e($tr['title'])?></h1><p class="muted"><?=e($from)?> – <?=e($to)?></p><table><thead><tr><th><?=e($tr['date'])?></th><th><?=e($tr['apartment'])?></th><th><?=e($tr['task'])?></th><th><?=e($tr['assigned'])?></th><th><?=e($tr['time'])?></th><th><?=e($tr['checklist'])?></th><th><?=e($tr['status'])?></th></tr></thead><tbody><?php foreach($rows as $r):$checks=json_decode((string)$r['checklist_json'],true)?:[];?><tr><td><?=e($r['task_date'])?><br><?=e(substr((string)$r['due_time'],0,5))?></td><td><b><?=e($r['apartment_code'])?></b><br><?=e($r['apartment_name'])?></td><td><?=e(HousekeepingWorkflow::taskTypeLabel((string)$r['task_type'],$lang))?><br><?=nl2br(e((string)$r['notes']))?></td><td><?=e($r['member_name']?:$r['team_name']?:$tr['open'])?></td><td><?=e((string)$r['estimated_minutes'])?> <?=e($tr['minutes'])?></td><td class="check"><?php foreach($checks as $c):?>☐ <?=e($c)?><br><?php endforeach?></td><td><?=e(HousekeepingWorkflow::statusLabel((string)$r['status'],$lang))?></td></tr><?php endforeach?></tbody></table><script>document.getElementById('printButton').addEventListener('click',()=>window.print());</script></body></html>
